ecom.minhhai.bookstore/Areas/Admin/Controllers/AdminRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ecom.minhhai.bookstore.Context;
using ecom.minhhai.bookstore.Models;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace ecom.minhhai.bookstore.Areas.Admin.Controllers
{
    //[Area("Admin")]
    /*public class AdminRoleController : Controller
    {
        private readonly BookStoreDbContext _context;
        public INotyfService _notyfService { get; }
        public AdminRoleController(BookStoreDbContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminRole
        public async Task<IActionResult> Index()
        {
            return _context.Roles != null ?
                        View(await _context.Roles.ToListAsync()) :
                        Problem("Entity set 'BookStoreDbContext.Roles'  is null.");
        }

        // GET: Admin/AdminRole/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var roleModel = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (roleModel == null)
            {
                return NotFound();
            }

            return View(roleModel);
        }

        // GET: Admin/AdminRole/Create  
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminRole/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoleId,RoleName")] RoleModel roleModel)
        {

            roleModel.RoleId = Guid.NewGuid();
            _context.Add(roleModel);
            await _context.SaveChangesAsync();
            _notyfService.Success("Tạo mới thành công");
            return RedirectToAction(nameof(Index));
        }

        // GET: Admin/AdminRole/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var roleModel = await _context.Roles.FindAsync(id);
            if (roleModel == null)
            {
                return NotFound();
            }
            return View(roleModel);
        }

        // POST: Admin/AdminRole/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("RoleId,RoleName")] RoleModel roleModel)
        {
            if (id != roleModel.RoleId)
            {
                return NotFound();
            }



            try
            {
                _context.Update(roleModel);
                await _context.SaveChangesAsync();
                _notyfService.Success("Sửa thành công");
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!RoleModelExists(roleModel.RoleId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));


        }

        // GET: Admin/AdminRole/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var roleModel = await _context.Roles
                .FirstOrDefaultAsync(m => m.RoleId == id);
            if (roleModel == null)
            {
                return NotFound();
            }

            return View(roleModel);
        }

        // POST: Admin/AdminRole/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Roles == null)
            {
                return Problem("Entity set 'BookStoreDbContext.Roles'  is null.");
            }
            var roleModel = await _context.Roles.FindAsync(id);
            if (roleModel != null)
            {
                _context.Roles.Remove(roleModel);
            }

            await _context.SaveChangesAsync();
            _notyfService.Success("Xóa Thành Công");
            return RedirectToAction(nameof(Index));
        }

        private bool RoleModelExists(Guid id)
        {
            return (_context.Roles?.Any(e => e.RoleId == id)).GetValueOrDefault();
        }
    }*/
}

ecom.minhhai.bookstore/Areas/Admin/Views/AdminRole/Create.cshtml
@model ecom.minhhai.bookstore.Models.RoleModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>RoleModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ecom.minhhai.bookstore/Areas/Admin/Views/AdminRole/Delete.cshtml
@model ecom.minhhai.bookstore.Models.RoleModel

@{
    ViewData["Title"] = "Xóa Quyền Truy Cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<hr />
<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />

    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleId)
        </dd>
    </dl>

    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RoleId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-secondary" asp-action="Index">Back to List</a>
    </form>
</div>

ecom.minhhai.bookstore/Areas/Admin/Views/AdminRole/Details.cshtml
@model ecom.minhhai.bookstore.Models.RoleModel

@{
    ViewData["Title"] = "Chi Tiết Quyền Đăng Nhập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Chi Tiết Quyền Đăng Nhập</h1>

<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleId)
        </dd>
    </dl>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoleName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoleName)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-sm btn-info" asp-action="Edit" asp-route-id="@Model?.RoleId">Edit</a> |
    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
</div>

ecom.minhhai.bookstore/Areas/Admin/Views/AdminRole/Edit.cshtml
@model ecom.minhhai.bookstore.Models.RoleModel

@{
    ViewData["Title"] = "Chỉnh Sửa Quyền Truy Cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Chỉnh Sửa Quyền Truy Cập</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RoleId" />
            <div class="form-group">
                <label asp-for="RoleId" class="control-label"></label>
                <input asp-for="RoleId" class="form-control" readonly />
                <span asp-validation-for="RoleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
</div>

ecom.minhhai.bookstore/Areas/Admin/Views/AdminRole/Index.cshtml
@model IEnumerable<ecom.minhhai.bookstore.Models.RoleModel>

@{
    ViewData["Title"] = "Quản Lý Quyền Truy Cập";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">Danh sách thành viên</h4>
                    </div>
                    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12 text-right">
                        <a asp-area="Admin" asp-controller="AdminRole" asp-action="Create" class="btn btn-sm btn-success">Thêm mới</a>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /row -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="white-box">
                            <div class="table-responsive">
                                <table class="table" id="example">
                                    <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Role Name</th>
                                            <th>#</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                @if(Model != null)
                                {
                                    foreach(var item in Model)
                                    {
                                        <tr>
                                            <td>@item.RoleId</td>
                                            <td>@item.RoleName</td>
                                            <td>
                                                <a class="btn btn-sm btn-info" asp-area="Admin" asp-controller="AdminRole" asp-action="Details" asp-route-id="@item.RoleId">View</a>
                                                <a class="btn btn-sm btn-primary" asp-area="Admin" asp-controller="AdminRole" asp-action="Edit" asp-route-id="@item.RoleId">Edit</a>
                                                <a class="btn btn-sm btn-danger" asp-area="Admin" asp-controller="AdminRole" asp-action="Delete" asp-route-id="@item.RoleId">Delete</a>
                                            </td>
                                        </tr>
                                    }
                                }
                                
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div>
        </div>