ecom.minhhai.bookstore/Areas/Admin/Controllers/AdminCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ecom.minhhai.bookstore.Context;
using ecom.minhhai.bookstore.Models;
using ecom.minhhai.bookstore.Infrastructure;
using PagedList.Core;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace ecom.minhhai.bookstore.Areas.Admin.Controllers
{
    [Authorize(Roles = AppicationRole.Admin)]
    [Area("Admin")]
    public class AdminCategoryController : Controller
    {
        private readonly BookStoreDbContext _context;
        public INotyfService _notyfService { get; }

        public AdminCategoryController(BookStoreDbContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminCategory
        public async Task<IActionResult> Index(int? page = 1)
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = Const.PAGE_SIZE;
            List<CategoryModel> listCategory = new List<CategoryModel>();
            listCategory = _context.Categories.AsNoTracking()
                    .OrderByDescending(x => x.CategoryId).ToList();

            PagedList<CategoryModel> models = new PagedList<CategoryModel>(listCategory.AsQueryable(), pageNumber, pageSize);
            //ViewBag.CurrentCateId = CatId;
            ViewBag.CurrentPage = pageNumber;
            //ViewData["Categories"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", CatId);
            return View(models);
        }

        // GET: Admin/AdminCategory/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var categoryModel = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (categoryModel == null)
            {
                return NotFound();
            }

            return View(categoryModel);
        }

        // GET: Admin/AdminCategory/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminCategory/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,CategoryName,Ordering,Published,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] CategoryModel categoryModel)
        {
            categoryModel.Alias = Extension.SeoURL(categoryModel.CategoryName);
            categoryModel.CategoryId = Guid.NewGuid();
            _context.Add(categoryModel);
            await _context.SaveChangesAsync();
            _notyfService.Success("Create Successfully");
            return RedirectToAction(nameof(Index));
        }

        // GET: Admin/AdminCategory/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var categoryModel = await _context.Categories.FindAsync(id);
            if (categoryModel == null)
            {
                return NotFound();
            }

            return View(categoryModel);
        }

        // POST: Admin/AdminCategory/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("CategoryId,CategoryName,Ordering,Published,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] CategoryModel categoryModel)
        {
            if (id != categoryModel.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoryModel);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Update Successfully");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryModelExists(categoryModel.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoryModel);
        }

        // GET: Admin/AdminCategory/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var categoryModel = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (categoryModel == null)
            {
                return NotFound();
            }

            return View(categoryModel);
        }

        // POST: Admin/AdminCategory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'BookStoreDbContext.Categories'  is null.");
            }
            var categoryModel = await _context.Categories.FindAsync(id);
            if (categoryModel != null)
            {
                _context.Categories.Remove(categoryModel);
                _notyfService.Success("Delete Successfully");
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryModelExists(Guid id)
        {
            return (_context.Categories?.Any(e => e.CategoryId == id)).GetValueOrDefault();
        }
    }
}

ecom.minhhai.bookstore/Areas/Admin/Views/AdminCategory/Create.cshtml
@model ecom.minhhai.bookstore.Models.CategoryModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>CategoryModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ordering" class="control-label"></label>
                <input asp-for="Ordering" class="form-control" />
                <span asp-validation-for="Ordering" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaDesc" class="control-label"></label>
                <input asp-for="MetaDesc" class="form-control" />
                <span asp-validation-for="MetaDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaKey" class="control-label"></label>
                <input asp-for="MetaKey" class="form-control" />
                <span asp-validation-for="MetaKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="control-label"></label>
                <input asp-for="Cover" class="form-control" />
                <span asp-validation-for="Cover" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SchemaMarkup" class="control-label"></label>
                <input asp-for="SchemaMarkup" class="form-control" />
                <span asp-validation-for="SchemaMarkup" class="text-danger"></span>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="true" asp-for="Published" name="Published">
              <label class="form-check-label" for="Published" style="color:white">
                Publish
              </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
</div>

ecom.minhhai.bookstore/Areas/Admin/Views/AdminCategory/Delete.cshtml
@model ecom.minhhai.bookstore.Models.CategoryModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete Category: @Model.CategoryName</h1>
<div>
    
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="AdminCategory" asp-action="Delete" asp-route-id="@Model.CategoryId" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryId" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-secondary" asp-action="Index">Back to List</a>
            <br />
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ordering" class="control-label"></label>
                <input type="number" asp-for="Ordering" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="Ordering" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaDesc" class="control-label"></label>
                <input asp-for="MetaDesc" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="MetaDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaKey" class="control-label"></label>
                <input asp-for="MetaKey" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="MetaKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="control-label"></label>
                <input asp-for="Cover" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="Cover" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SchemaMarkup" class="control-label"></label>
                <input asp-for="SchemaMarkup" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="SchemaMarkup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Published" class="control-label"></label>
                <input type="text" asp-for="Published" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="Published" class="text-danger"></span>
            </div>
            
        </form>
    </div>
</div>

ecom.minhhai.bookstore/Areas/Admin/Views/AdminCategory/Details.cshtml
@model ecom.minhhai.bookstore.Models.CategoryModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-id="@Model.CategoryId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryId" />
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ordering" class="control-label"></label>
                <input type="number" asp-for="Ordering" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="Ordering" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaDesc" class="control-label"></label>
                <input asp-for="MetaDesc" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="MetaDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaKey" class="control-label"></label>
                <input asp-for="MetaKey" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="MetaKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="control-label"></label>
                <input asp-for="Cover" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="Cover" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SchemaMarkup" class="control-label"></label>
                <input asp-for="SchemaMarkup" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="SchemaMarkup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Published" class="control-label"></label>
                <input type="text" asp-for="Published" class="form-control" disabled style="background-color: #2c2e33"/>
                <span asp-validation-for="Published" class="text-danger"></span>
            </div>
            
        </form>
    </div>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.CategoryId">Edit</a> |
    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
</div>

ecom.minhhai.bookstore/Areas/Admin/Views/AdminCategory/Edit.cshtml
@model ecom.minhhai.bookstore.Models.CategoryModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-route-id="@Model.CategoryId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CategoryId" />
            <div class="form-group">
                <label asp-for="CategoryName" class="control-label"></label>
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ordering" class="control-label"></label>
                <input type="number" asp-for="Ordering" class="form-control" />
                <span asp-validation-for="Ordering" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Alias" class="control-label"></label>
                <input asp-for="Alias" class="form-control" />
                <span asp-validation-for="Alias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaDesc" class="control-label"></label>
                <input asp-for="MetaDesc" class="form-control" />
                <span asp-validation-for="MetaDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MetaKey" class="control-label"></label>
                <input asp-for="MetaKey" class="form-control" />
                <span asp-validation-for="MetaKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="control-label"></label>
                <input asp-for="Cover" class="form-control" />
                <span asp-validation-for="Cover" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SchemaMarkup" class="control-label"></label>
                <input asp-for="SchemaMarkup" class="form-control" />
                <span asp-validation-for="SchemaMarkup" class="text-danger"></span>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="true" asp-for="Published" name="Published">
              <label class="form-check-label" for="Published" style="color:white">
                Publish
              </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary" asp-action="Index">Back to List</a>
</div>

ecom.minhhai.bookstore/Areas/Admin/Views/AdminCategory/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<ecom.minhhai.bookstore.Models.CategoryModel>

@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="container-fluid">

            <p>
                <a asp-action="Create" class="btn btn-sm btn-info">Create New Category</a>
            </p>
       <table class="table table-dark table-hover" style="margin-top: 20px">
            <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Category Name</th>
      <th scope="col">Ordering</th>
      <th scope="col">Status</th>
      <th scope="col">#</th>
    </tr>
  </thead>
  <tbody id="records_table" class="table-group-divider">
            @if(Model != null)
            {
               foreach (var item in Model)
                {
                     <tr>
                      <th scope="row">@item.CategoryId</th>
                      <td>@item.CategoryName</td>
                      <td>@item.Ordering</td>
                      <td>
                            @if (item.Published == false)
                            {
                                 <div class="d-flex align-items-center">
                                    <div class="  badge-dot badge badge-success m-r-1o"
                                    style=" background-color: red; border-radius: 50%; margin-right: 5px">
                                    </div>
                                    <div>Non Public</div>
                                </div>
                                
                            }
                            else
                            {
                                <div class="d-flex align-items-center">
                                    <div class="  badge-dot badge badge-success m-r-1o"
                                    style=" background-color: green; border-radius: 50%; margin-right: 5px">
                                </div>
                                    <div>Public</div>
                                </div>
                            }
                        </td>
                        <td>
                             <a class="btn btn-sm btn-info" asp-area="Admin" asp-controller="AdminCategory" asp-action="Details" asp-route-id="@item.CategoryId">View</a>
                             <a class="btn btn-sm btn-primary" asp-area="Admin" asp-controller="AdminCategory" asp-action="Edit" asp-route-id="@item.CategoryId">Edit</a>
                             <a class="btn btn-sm btn-danger" asp-area="Admin" asp-controller="AdminCategory" asp-action="Delete" asp-route-id="@item.CategoryId">Delete</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
       </table>
       <hr />
      <div aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item @(Model.HasPreviousPage ? "" : "disabled")">
                    <a class="page-link" asp-area="Admin" asp-controller="AdminCategory" asp-action="Index" asp-route-CatId="@ViewBag.CurrentCateId" asp-route-page="@(CurrentPage - 1)">Previous</a>
                </li>
                @for (var i = 1; i <= Model.PageNumber; i++)
                {
                    <li class="page-item @(i == CurrentPage ? "active" : "")">
                        <a class="page-link" asp-area="Admin" asp-controller="AdminCategory" asp-action="Index" asp-route-CatId="@ViewBag.CurrentCateId" asp-route-page="@i">@i</a>
                    </li>
                }
                <li class="page-item @(Model.HasNextPage ? "" : "disabled")">
                    <a class="page-link" asp-area="Admin" asp-controller="AdminCategory" asp-action="Index" asp-route-CatId="@ViewBag.CurrentCateId" asp-route-page="@(CurrentPage + 1)">Next</a>
                </li>
            </ul>
        </div>

       
</div>